apiVersion: v1
kind: Service
metadata:
  name: regression-tests-service
spec:
  selector:
    app: regression-tests
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer