apiVersion: v1
kind: Pod
metadata:
  name: test-runner
  labels:
    app: test-runner
spec:
  containers:
    - name: test-runner
      image: python-tests:latest
      imagePullPolicy: Never
      command: ["python", "runner.py"]
      ports:
        - containerPort: 8080
      volumeMounts:
        - mountPath: /app/tests-results
          name: test-results
  volumes:
    - name: test-results
      persistentVolumeClaim:
        claimName: test-results-pvc